name: Vulnerability scan

on:
  #schedule:
  #  - cron: "*/2 * * * *" # Run scan on Monday 04:00 UTC
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  vulnerability-scan:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: ./.github/actions/setup-go
      - name: Install OSV Scanner
        run: |
          go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - name: Run OSV Scanner
        id: osvscanner
        run: |
          SCANNER_OUT=$(osv-scanner --format json -r .)
          echo $SCANNER_OUT
      - name: Create an issue for OVS Scanner vulnerability
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $SCANNER_OUT | jq  -c '.results | .[].packages | .[]' | while read -r i; do
            packageName=$(echo "$i" | jq --raw-output '.package.name')
            echo "$i" | jq --raw-output '.vulnerabilities | .[] | .id' | while read -r issueID; do
              if [ "$(echo "$issues" | grep "$packageName:$issueID" > /dev/null; echo $?)" -eq 1 ]
              then
                gh issue create --title "OSV Scanner: $packageName:$issueID" --label cve --body "Description of the issue: https://osv.dev/$issueID"
              fi
            done
          done
